kind: pipeline
name: python37-buster

steps:
- name: build
  image: debian:buster-slim
  commands:
  - apt update -qq -y
  - apt install -qq -y build-essential fakeroot git python-all python3-cryptography python3-stdeb
  - git fetch --tags
  - sed "s/=determine_version()/='$(python3 setup.py --version)'/gi" -i setup.py
  - sed "s@('readme'@('share/doc/python3-acertmgr'@" -i setup.py
  - python3 setup.py --command-packages=stdeb.command bdist_deb
  - python3 setup.py --version > version.github
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    draft: true
    files: deb_dist/*.deb
    title: version.github
  when:
    event: tag
